### ISSUE TITLE
thread 'main' panicked at src/query/date.rs:60:87: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by bbigras** [pacman82/odbc2parquet#536]
```
thread 'main' panicked at src/query/date.rs:60:87:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::Option<T>::unwrap
             at /build/rustc-1.75.0-src/library/core/src/option.rs:931:21
   4: odbc2parquet::query::date::days_since_epoch
             at /home/bbigras/src/odbc2parquet/src/query/date.rs:60:9
   5: core::ops::function::FnOnce::call_once
             at /build/rustc-1.75.0-src/library/core/src/ops/function.rs:250:5
   6: core::option::Option<T>::map
             at /build/rustc-1.75.0-src/library/core/src/option.rs:1072:29
   7: <odbc2parquet::query::date::Date as odbc2parquet::query::column_strategy::ColumnStrategy>::copy_odbc_to_parquet::{{closure}}
             at /home/bbigras/src/odbc2parquet/src/query/date.rs:51:68
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /build/rustc-1.75.0-src/library/core/src/ops/function.rs:305:13
   9: core::option::Option<T>::map
             at /build/rustc-1.75.0-src/library/core/src/option.rs:1072:29
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /build/rustc-1.75.0-src/library/core/src/iter/adapters/map.rs:103:26
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /build/rustc-1.75.0-src/library/core/src/iter/adapters/map.rs:103:9
  12: <core::iter::adapters::zip::Zip<A,B> as core::iter::adapters::zip::ZipImpl<A,B>>::next
             at /build/rustc-1.75.0-src/library/core/src/iter/adapters/zip.rs:165:21
  13: <core::iter::adapters::zip::Zip<A,B> as core::iter::traits::iterator::Iterator>::next
             at /build/rustc-1.75.0-src/library/core/src/iter/adapters/zip.rs:84:9
  14: odbc2parquet::parquet_buffer::ParquetBuffer::write_optional_any_falliable
             at /home/bbigras/src/odbc2parquet/src/parquet_buffer.rs:85:41
  15: odbc2parquet::parquet_buffer::ParquetBuffer::write_optional
             at /home/bbigras/src/odbc2parquet/src/parquet_buffer.rs:125:9
  16: <odbc2parquet::query::date::Date as odbc2parquet::query::column_strategy::ColumnStrategy>::copy_odbc_to_parquet
             at /home/bbigras/src/odbc2parquet/src/query/date.rs:51:9
  17: odbc2parquet::query::table_strategy::ColumnExporter::export_nth_column
             at /home/bbigras/src/odbc2parquet/src/query/table_strategy.rs:181:9
  18: odbc2parquet::query::current_file::CurrentFile::write_row_group
             at /home/bbigras/src/odbc2parquet/src/query/current_file.rs:54:13
  19: <odbc2parquet::query::parquet_writer::FileWriter as odbc2parquet::query::parquet_writer::ParquetOutput>::write_row_group
             at /home/bbigras/src/odbc2parquet/src/query/parquet_writer.rs:154:25
  20: odbc2parquet::query::table_strategy::TableStrategy::write_batch
             at /home/bbigras/src/odbc2parquet/src/query/table_strategy.rs:160:9
  21: odbc2parquet::query::table_strategy::TableStrategy::block_cursor_to_parquet
             at /home/bbigras/src/odbc2parquet/src/query/table_strategy.rs:138:13
  22: odbc2parquet::query::cursor_to_parquet
             at /home/bbigras/src/odbc2parquet/src/query.rs:128:5
  23: odbc2parquet::query::query
             at /home/bbigras/src/odbc2parquet/src/query.rs:88:9
  24: odbc2parquet::main
             at /home/bbigras/src/odbc2parquet/src/main.rs:327:13
  25: core::ops::function::FnOnce::call_once
             at /build/rustc-1.75.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

6dd09053187957b0b4dc3e416b3ba447e5e65c3b with:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 5a3355c..48b534f 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -57,7 +57,7 @@ odbc-api = "6"
 # importantly, UTF-8 is likely to be more battled tested on these platforms, while UTF-16 is "only"
 # required by the standard.
 [target.'cfg(not(target_os = "windows"))'.dependencies]
-odbc-api = { version = "6", features = ["narrow"] }
+odbc-api = { version = "6", features = ["iodbc", "narrow"] }

 [dev-dependencies]
 assert_cmd = "2.0.14"
```

with hfsql, a shitty sql

**Comment by bbigras** [comment]
Yeah I think I got some 0.

**Comment by pacman82** [comment]
I think you need to change more than linking against iodbc. Probably you kind of need your own fork for your driver. As long as you can fetch strings there is a chance for success.

Then fetching dates directly does not work I would suggest changing this struct to use a narrow text buffer for fetching. After that Parsing the date instead interpreting the doc date structure

**Comment by pacman82** [comment]
If you want to spend time making this work for you, I may find the time on Friday to give you some pointers.

**Comment by pacman82** [comment]
I am a bit confused, what do you mean by dates with `0`? Does this mean you get a zeroed out date struct back from your driver? By any chance related to dates being NULL on the database?

**Comment by pacman82** [comment]
From your comment I take you could adapt the code, so it works for you? Closing this issue, but feel free to reopen if my assesement is wrong.
