### ISSUE TITLE
Length indicator must be non-negative.: TryFromIntError(())

### ISSUE THREAD

**Issue by cliveeisen** [pacman82/odbc2parquet#663]
First time odbs2parquet user here. Can anyone see what I am doing wrong?

RUST_BACKTRACE=full odbc2parquet -vvv query  --dsn ovomdr  hid_to_mac.par "select * from hid_to_mac"
2024-11-07T17:27:40+00:00 - DEBUG ODBC Environment created.
2024-11-07T17:27:40+00:00 - DEBUG Setting ODBC API version to Odbc3
2024-11-07T17:27:40+00:00 - DEBUG SQLAllocHandle allocated connection (Dbc) handle '0x55ee077a65b0'
2024-11-07T17:27:40+00:00 - INFO Database Management System Name: Informix
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 1: name: 'hid', relational type: 'Char { length: Some(32) }', nullability: NoNulls
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 1: Text { max_str_len: 128 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 2: name: 'mac', relational type: 'Char { length: Some(12) }', nullability: NoNulls
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 2: Text { max_str_len: 48 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 3: name: 'created', relational type: 'Timestamp { precision: 0 }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 3: Timestamp { nullable: true }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 4: name: 'appid', relational type: 'Char { length: Some(32) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 4: Text { max_str_len: 128 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 5: name: 'description', relational type: 'Varchar { length: Some(128) }', nullability: NoNulls
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 5: Text { max_str_len: 512 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 6: name: 'accno', relational type: 'Char { length: Some(30) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 6: Text { max_str_len: 120 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 7: name: 'mpan', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 7: Text { max_str_len: 80 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 8: name: 'mprn', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 8: Text { max_str_len: 80 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 9: name: 'eui', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 9: Text { max_str_len: 80 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 10: name: 'pslk', relational type: 'Char { length: Some(32) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 10: Text { max_str_len: 128 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 11: name: 'eserial', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 11: Text { max_str_len: 80 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 12: name: 'gserial', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 12: Text { max_str_len: 80 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 13: name: 'hserial', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 13: Text { max_str_len: 80 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 14: name: 'cserial', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 14: Text { max_str_len: 80 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 15: name: 'iserial', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 15: Text { max_str_len: 80 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 16: name: 'alerts', relational type: 'Integer', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 16: I32 { nullable: true }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 17: name: 'publish', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 17: Text { max_str_len: 80 }
2024-11-07T17:27:40+00:00 - DEBUG ODBC column description for column 18: name: 'tariffsrc', relational type: 'Char { length: Some(1) }', nullability: NoNulls
2024-11-07T17:27:40+00:00 - DEBUG ODBC buffer description for column at index 18: Text { max_str_len: 4 }
2024-11-07T17:27:40+00:00 - INFO Memory usage per row is 2027 bytes. This excludes memory directly allocated by the ODBC driver.
2024-11-07T17:27:40+00:00 - INFO Batch size set to 65535 rows.
2024-11-07T17:27:40+00:00 - INFO Fetched batch 1 with 65535 rows.
2024-11-07T17:27:40+00:00 - INFO Fetched 65535 rows in total.
2024-11-07T17:27:40+00:00 - DEBUG Writing column with index 0 and name 'hid'.
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/odbc-api-9.0.0/src/buffers/indicator.rs:25:22:
Length indicator must be non-negative.: TryFromIntError(())
stack backtrace:
   0:     0x55ee06f6fcf9 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
   1:     0x55ee06d5cd7b - core::fmt::write::hf5713710ce10ff22
   2:     0x55ee06f41e32 - std::io::Write::write_fmt::hda708db57927dacf
   3:     0x55ee06f70db8 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
   4:     0x55ee06f71c56 - std::panicking::rust_panic_with_hook::had2118629c312a4a
   5:     0x55ee06f71755 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
   6:     0x55ee06f716b9 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
   7:     0x55ee06f716a4 - rust_begin_unwind
   8:     0x55ee06cc7872 - core::panicking::panic_fmt::h3eea515d05f7a35e
   9:     0x55ee06cc7bf5 - core::result::unwrap_failed::h7c8d8bbbcf45dc13
  10:     0x55ee06e3426e - <odbc_api::buffers::text_column::TextColumnIt<u8> as core::iter::traits::iterator::Iterator>::next::he5c722b56d72eb53
  11:     0x55ee06dc2b3e - <odbc2parquet::query::text::Utf8 as odbc2parquet::query::column_strategy::ColumnStrategy>::copy_odbc_to_parquet::h277cd67f93931358
  12:     0x55ee06cd7d5a - odbc2parquet::query::conversion_strategy::ColumnExporter::export_nth_column::h2e8b775e0fc4ce3f
  13:     0x55ee06da7ffb - odbc2parquet::query::current_file::CurrentFile::write_row_group::h89b23a2b61d54d3a
  14:     0x55ee06dea245 - <odbc2parquet::query::parquet_writer::FileWriter as odbc2parquet::query::parquet_writer::ParquetOutput>::write_row_group::h5ad104c031af93c6
  15:     0x55ee06cd7575 - odbc2parquet::query::conversion_strategy::ConversionStrategy::block_cursor_to_parquet::h44b3ea86da753a84
  16:     0x55ee06db0590 - odbc2parquet::query::query::h4b9f996ec9878474
  17:     0x55ee06e1c509 - odbc2parquet::main::he8408035b0c64693
  18:     0x55ee06e02993 - std::sys::backtrace::__rust_begin_short_backtrace::h73a238f1d0cc4d99
  19:     0x55ee06e18ff2 - main
  20:     0x7f19acb9d24a - <unknown>
  21:     0x7f19acb9d305 - __libc_start_main
  22:     0x55ee06ccf775 - _start
  23:                0x0 - <unknown>
Aborted

**Comment by pacman82** [comment]
I do not think, you are doing something wrong here, but I have not run across the `informix` driver before. Maybe it is doing something unexpected. Would you be so kind as to run an experiment and share the debug log with me:

 Run with a smaller batch size which would fit into a signed 16Bit integer. You can do so by setting `--batch-size-row 32767` for the query sub-command.

**Comment by cliveeisen** [comment]
Thanks so much for the swift response

Sadly no change

RUST_BACKTRACE=full odbc2parquet -vvv query  --dsn ovomdr  --batch-size-row 32767 hid_to_mac.par "select * from hid_to_mac"
2024-11-08T10:18:22+00:00 - DEBUG ODBC Environment created.
2024-11-08T10:18:22+00:00 - DEBUG Setting ODBC API version to Odbc3
2024-11-08T10:18:22+00:00 - DEBUG SQLAllocHandle allocated connection (Dbc) handle '0x5643eb6465b0'
2024-11-08T10:18:22+00:00 - INFO Database Management System Name: Informix
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 1: name: 'hid', relational type: 'Char { length: Some(32) }', nullability: NoNulls
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 1: Text { max_str_len: 128 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 2: name: 'mac', relational type: 'Char { length: Some(12) }', nullability: NoNulls
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 2: Text { max_str_len: 48 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 3: name: 'created', relational type: 'Timestamp { precision: 0 }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 3: Timestamp { nullable: true }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 4: name: 'appid', relational type: 'Char { length: Some(32) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 4: Text { max_str_len: 128 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 5: name: 'description', relational type: 'Varchar { length: Some(128) }', nullability: NoNulls
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 5: Text { max_str_len: 512 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 6: name: 'accno', relational type: 'Char { length: Some(30) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 6: Text { max_str_len: 120 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 7: name: 'mpan', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 7: Text { max_str_len: 80 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 8: name: 'mprn', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 8: Text { max_str_len: 80 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 9: name: 'eui', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 9: Text { max_str_len: 80 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 10: name: 'pslk', relational type: 'Char { length: Some(32) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 10: Text { max_str_len: 128 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 11: name: 'eserial', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 11: Text { max_str_len: 80 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 12: name: 'gserial', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 12: Text { max_str_len: 80 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 13: name: 'hserial', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 13: Text { max_str_len: 80 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 14: name: 'cserial', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 14: Text { max_str_len: 80 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 15: name: 'iserial', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 15: Text { max_str_len: 80 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 16: name: 'alerts', relational type: 'Integer', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 16: I32 { nullable: true }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 17: name: 'publish', relational type: 'Char { length: Some(20) }', nullability: Nullable
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 17: Text { max_str_len: 80 }
2024-11-08T10:18:22+00:00 - DEBUG ODBC column description for column 18: name: 'tariffsrc', relational type: 'Char { length: Some(1) }', nullability: NoNulls
2024-11-08T10:18:22+00:00 - DEBUG ODBC buffer description for column at index 18: Text { max_str_len: 4 }
2024-11-08T10:18:22+00:00 - INFO Memory usage per row is 2027 bytes. This excludes memory directly allocated by the ODBC driver.
2024-11-08T10:18:22+00:00 - INFO Batch size set to 32767 rows.
2024-11-08T10:18:22+00:00 - INFO Fetched batch 1 with 32767 rows.
2024-11-08T10:18:22+00:00 - INFO Fetched 32767 rows in total.
2024-11-08T10:18:22+00:00 - DEBUG Writing column with index 0 and name 'hid'.
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/odbc-api-9.0.0/src/buffers/indicator.rs:25:22:
Length indicator must be non-negative.: TryFromIntError(())
stack backtrace:
   0:     0x5643eb248cf9 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
   1:     0x5643eb035d7b - core::fmt::write::hf5713710ce10ff22
   2:     0x5643eb21ae32 - std::io::Write::write_fmt::hda708db57927dacf
   3:     0x5643eb249db8 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
   4:     0x5643eb24ac56 - std::panicking::rust_panic_with_hook::had2118629c312a4a
   5:     0x5643eb24a755 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
   6:     0x5643eb24a6b9 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
   7:     0x5643eb24a6a4 - rust_begin_unwind
   8:     0x5643eafa0872 - core::panicking::panic_fmt::h3eea515d05f7a35e
   9:     0x5643eafa0bf5 - core::result::unwrap_failed::h7c8d8bbbcf45dc13
  10:     0x5643eb10d26e - <odbc_api::buffers::text_column::TextColumnIt<u8> as core::iter::traits::iterator::Iterator>::next::he5c722b56d72eb53
  11:     0x5643eb09bb3e - <odbc2parquet::query::text::Utf8 as odbc2parquet::query::column_strategy::ColumnStrategy>::copy_odbc_to_parquet::h277cd67f93931358
  12:     0x5643eafb0d5a - odbc2parquet::query::conversion_strategy::ColumnExporter::export_nth_column::h2e8b775e0fc4ce3f
  13:     0x5643eb080ffb - odbc2parquet::query::current_file::CurrentFile::write_row_group::h89b23a2b61d54d3a
  14:     0x5643eb0c3245 - <odbc2parquet::query::parquet_writer::FileWriter as odbc2parquet::query::parquet_writer::ParquetOutput>::write_row_group::h5ad104c031af93c6
  15:     0x5643eafb0575 - odbc2parquet::query::conversion_strategy::ConversionStrategy::block_cursor_to_parquet::h44b3ea86da753a84
  16:     0x5643eb089590 - odbc2parquet::query::query::h4b9f996ec9878474
  17:     0x5643eb0f5509 - odbc2parquet::main::he8408035b0c64693
  18:     0x5643eb0db993 - std::sys::backtrace::__rust_begin_short_backtrace::h73a238f1d0cc4d99
  19:     0x5643eb0f1ff2 - main
  20:     0x7f2afa3c024a - <unknown>
  21:     0x7f2afa3c0305 - __libc_start_main
  22:     0x5643eafa8775 - _start
  23:                0x0 - <unknown>
Aborted


Here is the table schema in case that has a clue - other table select seem to work

create table "informix".hid_to_mac 
  (
    hid char(32) not null ,
    mac char(12) not null ,
    created datetime year to second 
        default current year to second,
    appid char(32),
    description varchar(128) 
        default '' not null ,
    accno char(30),
    mpan char(20),
    mprn char(20),
    eui char(20),
    pslk char(32),
    eserial char(20),
    gserial char(20),
    hserial char(20),
    cserial char(20),
    iserial char(20),
    alerts integer 
        default 0,
    publish char(20),
    tariffsrc char(1) 
        default 'm' not null 
  ) 
— 
Clive Eisen

**Comment by cliveeisen** [comment]
We have done some more testing and it seems that columns of type char(n) or varchar(n) all fail
integers datetime and so on are fine.

Hope this helps.

Regards,

— 
Clive Eisen

**Comment by pacman82** [comment]
Hello @cliveeisen ,

yes this observation is in line with a more careful read of the backtrace. The length indicator which is negative is not about the batch size, but describing the length of a string. This is likely a bug in the driver. In the past (I might find the according issues later) this could be fixed by using drivers more suitable for the architecture. I would encourage you to see if your ODBC driver is a) up to date and b) if there is a different variant.

The most likely root cause I can see currently is, that the driver is written against an erroneous interpretation of the ODBC spec, which assumed the wrong integer size for reporting lengths. It is worth investigating whether there is a variant which fixes this issue.

best, Markus

**Comment by pacman82** [comment]
Hello @cliveeisen ,

here I found the relevant issue from the past. It has occurred for IBM db2. Here IBM provided different drivers which did implement the ODBC standard correctly.

See: <https://github.com/pacman82/arrow-odbc-py/issues/78#issuecomment-1915672063>

The relevant part here is that for db2 you need to carefully consider your architecture, as well as be aware if you are using a 32 Bit or 64 Bit driver manager. I think it might just be very similar for the "Informix" system your locks mention.

Best, Markus

**Comment by pacman82** [comment]
Long story short: if you are on a 64Bit platform you likely need an `Informix` driver which is build assuming `SQLLEN` is 64Bit rather than 32Bit. Alternatively you can use the 32Bit drivers. On 32Bit Platforms `SQLLEN` is actually 32Bit large, which may also take care of your problem.

If you are on windows there is a 32Bit version of odbc2parquet released. I could help you build the 32Bit version on other platforms.

Best, Markus

**Comment by pacman82** [comment]
Improved panic message in upstream `odbc-api` for this case, hinting at a driver problem. Closing this issue. Feel free to reopen if new information emerges.
