### ISSUE TITLE
insert: source slice length (22931) does not match destination slice length (32767)

### ISSUE THREAD

**Issue by matchaEis** [pacman82/odbc2parquet#665]
Hello Markus, first of all I would like to thank for this great project and your continuous care for it. I'm using odbc2parquet for quite a while to write data from odbc sources into parquet files. Today I started to evaluate your "insert" capability.
I created a parquet file (obviously with odbc2parquet) and tried to insert the content of the file into a database (EXASOL) with this command:

`odbc2parquet.exe -vvv insert --dsn test test.parquet test.B_BSTD_VERTRAG`

As expected it starts inserting each row group of the parquet file into the database. At the last row group the programm crashes with this error:

_2024-11-12T15:34:07+01:00 - DEBUG ODBC Environment created.
2024-11-12T15:34:07+01:00 - DEBUG Setting ODBC API version to Odbc3
2024-11-12T15:34:07+01:00 - DEBUG SQLAllocHandle allocated connection (Dbc) handle '0x1a25cd16a80'
2024-11-12T15:34:07+01:00 - INFO Insert statement Text: INSERT INTO test.B_BSTD_VERTRAG (BSV_EDV_NR, INST_NR, BSV_TYP_KZ, VTRK_EDV_NR, VTRKR_EDV_NR, RVKRL_EDV_NR, VTRP_EDV_NR, VTRPR_EDV_NR, RVPRL_EDV_NR, VTRPP_EDV_NR, BSV_VTR_MNG, BSV_VTR_WERT, BSV_VTR_AUFT_MNG, BSV_ANG_MNG, BSV_ANG_WERT, BSV_BST_MNG, BSV_BST_WERT, BSV_DSP_MNG, BSV_DSP_WERT, BSV_TRS_MNG, BSV_TRS_WERT, BSV_GEL_MNG, BSV_GEL_WERT, BSV_RG_MNG, BSV_RG_WERT, BSV_D1_MNG, BSV_D1_WERT, BSV_D2_MNG, BSV_D2_WERT, BSV_D3_MNG, BSV_D3_WERT, BSV_STS, BSV_ANL_STAMP, BSV_AEN_STAMP, BEN_ANL_NR, BEN_AEN_NR) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
2024-11-12T15:34:07+01:00 - INFO Insert row group 0 of 129.
2024-11-12T15:34:07+01:00 - DEBUG SQLFreeHandle dropped 0x1a25cd184c0 of type Stmt.
2024-11-12T15:34:07+01:00 - DEBUG Rebinding text column buffer with 0 elements. Maximum string length 1 => 3
2024-11-12T15:34:08+01:00 - INFO Insert row group 1 of 129.
2024-11-12T15:34:09+01:00 - INFO Insert row group 2 of 129.
2024-11-12T15:34:10+01:00 - INFO Insert row group 3 of 129.
2024-11-12T15:34:11+01:00 - INFO Insert row group 4 of 129.
2024-11-12T15:34:12+01:00 - INFO Insert row group 5 of 129.
2024-11-12T15:34:13+01:00 - INFO Insert row group 6 of 129.
2024-11-12T15:34:14+01:00 - INFO Insert row group 7 of 129.
2024-11-12T15:34:15+01:00 - INFO Insert row group 8 of 129.
2024-11-12T15:34:16+01:00 - INFO Insert row group 9 of 129.
2024-11-12T15:34:17+01:00 - INFO Insert row group 10 of 129.
2024-11-12T15:34:18+01:00 - INFO Insert row group 11 of 129.
2024-11-12T15:34:20+01:00 - INFO Insert row group 12 of 129.
2024-11-12T15:34:20+01:00 - INFO Insert row group 13 of 129.
2024-11-12T15:34:21+01:00 - INFO Insert row group 14 of 129.
2024-11-12T15:34:22+01:00 - INFO Insert row group 15 of 129.
2024-11-12T15:34:23+01:00 - INFO Insert row group 16 of 129.
2024-11-12T15:34:24+01:00 - INFO Insert row group 17 of 129.
2024-11-12T15:34:25+01:00 - INFO Insert row group 18 of 129.
2024-11-12T15:34:26+01:00 - INFO Insert row group 19 of 129.
2024-11-12T15:34:27+01:00 - INFO Insert row group 20 of 129.
2024-11-12T15:34:28+01:00 - INFO Insert row group 21 of 129.
2024-11-12T15:34:29+01:00 - INFO Insert row group 22 of 129.
2024-11-12T15:34:30+01:00 - INFO Insert row group 23 of 129.
2024-11-12T15:34:31+01:00 - INFO Insert row group 24 of 129.
2024-11-12T15:34:32+01:00 - INFO Insert row group 25 of 129.
2024-11-12T15:34:33+01:00 - INFO Insert row group 26 of 129.
2024-11-12T15:34:34+01:00 - INFO Insert row group 27 of 129.
2024-11-12T15:34:36+01:00 - INFO Insert row group 28 of 129.
2024-11-12T15:34:37+01:00 - INFO Insert row group 29 of 129.
2024-11-12T15:34:38+01:00 - INFO Insert row group 30 of 129.
2024-11-12T15:34:39+01:00 - INFO Insert row group 31 of 129.
2024-11-12T15:34:40+01:00 - INFO Insert row group 32 of 129.
2024-11-12T15:34:41+01:00 - INFO Insert row group 33 of 129.
2024-11-12T15:34:42+01:00 - INFO Insert row group 34 of 129.
2024-11-12T15:34:44+01:00 - INFO Insert row group 35 of 129.
2024-11-12T15:34:45+01:00 - INFO Insert row group 36 of 129.
2024-11-12T15:34:46+01:00 - INFO Insert row group 37 of 129.
2024-11-12T15:34:47+01:00 - INFO Insert row group 38 of 129.
2024-11-12T15:34:48+01:00 - INFO Insert row group 39 of 129.
2024-11-12T15:34:49+01:00 - INFO Insert row group 40 of 129.
2024-11-12T15:34:50+01:00 - INFO Insert row group 41 of 129.
2024-11-12T15:34:51+01:00 - INFO Insert row group 42 of 129.
2024-11-12T15:34:52+01:00 - INFO Insert row group 43 of 129.
2024-11-12T15:34:53+01:00 - INFO Insert row group 44 of 129.
2024-11-12T15:34:54+01:00 - INFO Insert row group 45 of 129.
2024-11-12T15:34:55+01:00 - INFO Insert row group 46 of 129.
2024-11-12T15:34:57+01:00 - INFO Insert row group 47 of 129.
2024-11-12T15:34:58+01:00 - INFO Insert row group 48 of 129.
2024-11-12T15:34:59+01:00 - INFO Insert row group 49 of 129.
2024-11-12T15:35:00+01:00 - INFO Insert row group 50 of 129.
2024-11-12T15:35:01+01:00 - INFO Insert row group 51 of 129.
2024-11-12T15:35:02+01:00 - INFO Insert row group 52 of 129.
2024-11-12T15:35:03+01:00 - INFO Insert row group 53 of 129.
2024-11-12T15:35:04+01:00 - INFO Insert row group 54 of 129.
2024-11-12T15:35:05+01:00 - INFO Insert row group 55 of 129.
2024-11-12T15:35:06+01:00 - INFO Insert row group 56 of 129.
2024-11-12T15:35:07+01:00 - INFO Insert row group 57 of 129.
2024-11-12T15:35:08+01:00 - INFO Insert row group 58 of 129.
2024-11-12T15:35:09+01:00 - INFO Insert row group 59 of 129.
2024-11-12T15:35:10+01:00 - INFO Insert row group 60 of 129.
2024-11-12T15:35:11+01:00 - INFO Insert row group 61 of 129.
2024-11-12T15:35:12+01:00 - INFO Insert row group 62 of 129.
2024-11-12T15:35:13+01:00 - INFO Insert row group 63 of 129.
2024-11-12T15:35:14+01:00 - INFO Insert row group 64 of 129.
2024-11-12T15:35:15+01:00 - INFO Insert row group 65 of 129.
2024-11-12T15:35:16+01:00 - INFO Insert row group 66 of 129.
2024-11-12T15:35:16+01:00 - INFO Insert row group 67 of 129.
2024-11-12T15:35:17+01:00 - INFO Insert row group 68 of 129.
2024-11-12T15:35:18+01:00 - INFO Insert row group 69 of 129.
2024-11-12T15:35:19+01:00 - INFO Insert row group 70 of 129.
2024-11-12T15:35:20+01:00 - INFO Insert row group 71 of 129.
2024-11-12T15:35:21+01:00 - INFO Insert row group 72 of 129.
2024-11-12T15:35:22+01:00 - INFO Insert row group 73 of 129.
2024-11-12T15:35:23+01:00 - INFO Insert row group 74 of 129.
2024-11-12T15:35:24+01:00 - INFO Insert row group 75 of 129.
2024-11-12T15:35:24+01:00 - INFO Insert row group 76 of 129.
2024-11-12T15:35:25+01:00 - INFO Insert row group 77 of 129.
2024-11-12T15:35:26+01:00 - INFO Insert row group 78 of 129.
2024-11-12T15:35:27+01:00 - INFO Insert row group 79 of 129.
2024-11-12T15:35:28+01:00 - INFO Insert row group 80 of 129.
2024-11-12T15:35:29+01:00 - INFO Insert row group 81 of 129.
2024-11-12T15:35:30+01:00 - INFO Insert row group 82 of 129.
2024-11-12T15:35:31+01:00 - INFO Insert row group 83 of 129.
2024-11-12T15:35:32+01:00 - INFO Insert row group 84 of 129.
2024-11-12T15:35:33+01:00 - INFO Insert row group 85 of 129.
2024-11-12T15:35:34+01:00 - INFO Insert row group 86 of 129.
2024-11-12T15:35:35+01:00 - INFO Insert row group 87 of 129.
2024-11-12T15:35:36+01:00 - INFO Insert row group 88 of 129.
2024-11-12T15:35:37+01:00 - INFO Insert row group 89 of 129.
2024-11-12T15:35:38+01:00 - INFO Insert row group 90 of 129.
2024-11-12T15:35:39+01:00 - INFO Insert row group 91 of 129.
2024-11-12T15:35:40+01:00 - INFO Insert row group 92 of 129.
2024-11-12T15:35:41+01:00 - INFO Insert row group 93 of 129.
2024-11-12T15:35:42+01:00 - INFO Insert row group 94 of 129.
2024-11-12T15:35:43+01:00 - INFO Insert row group 95 of 129.
2024-11-12T15:35:44+01:00 - INFO Insert row group 96 of 129.
2024-11-12T15:35:45+01:00 - INFO Insert row group 97 of 129.
2024-11-12T15:35:46+01:00 - INFO Insert row group 98 of 129.
2024-11-12T15:35:47+01:00 - INFO Insert row group 99 of 129.
2024-11-12T15:35:48+01:00 - INFO Insert row group 100 of 129.
2024-11-12T15:35:49+01:00 - INFO Insert row group 101 of 129.
2024-11-12T15:35:50+01:00 - INFO Insert row group 102 of 129.
2024-11-12T15:35:51+01:00 - INFO Insert row group 103 of 129.
2024-11-12T15:35:51+01:00 - INFO Insert row group 104 of 129.
2024-11-12T15:35:52+01:00 - INFO Insert row group 105 of 129.
2024-11-12T15:35:53+01:00 - INFO Insert row group 106 of 129.
2024-11-12T15:35:54+01:00 - INFO Insert row group 107 of 129.
2024-11-12T15:35:55+01:00 - INFO Insert row group 108 of 129.
2024-11-12T15:35:56+01:00 - INFO Insert row group 109 of 129.
2024-11-12T15:35:57+01:00 - INFO Insert row group 110 of 129.
2024-11-12T15:35:58+01:00 - INFO Insert row group 111 of 129.
2024-11-12T15:35:59+01:00 - INFO Insert row group 112 of 129.
2024-11-12T15:35:59+01:00 - INFO Insert row group 113 of 129.
2024-11-12T15:36:01+01:00 - INFO Insert row group 114 of 129.
2024-11-12T15:36:02+01:00 - INFO Insert row group 115 of 129.
2024-11-12T15:36:03+01:00 - INFO Insert row group 116 of 129.
2024-11-12T15:36:04+01:00 - INFO Insert row group 117 of 129.
2024-11-12T15:36:05+01:00 - INFO Insert row group 118 of 129.
2024-11-12T15:36:06+01:00 - INFO Insert row group 119 of 129.
2024-11-12T15:36:07+01:00 - INFO Insert row group 120 of 129.
2024-11-12T15:36:07+01:00 - INFO Insert row group 121 of 129.
2024-11-12T15:36:08+01:00 - INFO Insert row group 122 of 129.
2024-11-12T15:36:09+01:00 - INFO Insert row group 123 of 129.
2024-11-12T15:36:10+01:00 - INFO Insert row group 124 of 129.
2024-11-12T15:36:11+01:00 - INFO Insert row group 125 of 129.
2024-11-12T15:36:12+01:00 - INFO Insert row group 126 of 129.
2024-11-12T15:36:14+01:00 - INFO Insert row group 127 of 129.
2024-11-12T15:36:15+01:00 - INFO Insert row group 128 of 129.
thread 'main' panicked at src\insert.rs:303:28:
source slice length (22931) does not match destination slice length (32767)
stack backtrace:
   0:     0x7ff755dcb5c3 - <unknown>
   1:     0x7ff755bdca29 - <unknown>
   2:     0x7ff755dbc9f7 - <unknown>
   3:     0x7ff755dcc8c7 - <unknown>
   4:     0x7ff755dcd8ef - <unknown>
   5:     0x7ff755dcd346 - <unknown>
   6:     0x7ff755dcd29f - <unknown>
   7:     0x7ff755dcd286 - <unknown>
   8:     0x7ff755e61ac4 - <unknown>
   9:     0x7ff755e6211e - <unknown>
  10:     0x7ff755b58730 - <unknown>
  11:     0x7ff755c36448 - <unknown>
  12:     0x7ff755c6798c - <unknown>
  13:     0x7ff755ca8866 - <unknown>
  14:     0x7ff755c62402 - <unknown>
  15:     0x7ff755e5095c - <unknown>
  16:     0x7fff2cf07ac4 - BaseThreadInitThunk
  17:     0x7fff2d9ea8c1 - RtlUserThreadStart_

The last row group in the parquet file is indeed 22931 rows long instead of 32767 like all other row groups:

`┌──────────────┬────────────────────┐
│ row_group_id │ row_group_num_rows │
│    int64     │       int64        │
├──────────────┼────────────────────┤
│          128 │              22931 │`

It would be awesome if you can help me with this. Thank you :)

Max

**Comment by matchaEis** [comment]
I tried a different parquet file and got the same error:

`2024-11-12T15:47:15+01:00 - INFO Insert row group 124 of 125.
thread 'main' panicked at src\insert.rs:303:28:
source slice length (10591) does not match destination slice length (32767)`

**Comment by pacman82** [comment]
Hello @matchaEis ,

thanks for the kind works. Seems like a straight forward bug in `odbc2parquet`. Sorry for that. Easy enough, to fix I think. Most effort will be writing a nice reproducing test. If I am not to tired, I may be able to do so after work.

Best, Markus

**Comment by matchaEis** [comment]
Hello @pacman82 ,

thank you very much. 
for me it doesn't have to be that fast, so take your time :) 

Best, Max

**Comment by pacman82** [comment]
Hello @matchaEis ,

`odbc2parquet 6.3.1` is released and ships a fix.

Best Markus

**Comment by matchaEis** [comment]
Hello @pacman82,

it works flawless now. Thank you!

Best Max
